const {chromium}=require('/Users/arijitroy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url='file:///Users/arijitroy/Documents/ChatGPT/NASA/research-report.html';
 await page.goto(url);
 await page.screenshot({path:'output/qa/report-desktop.png'});
 await page.locator('#search').fill('calibration');
 const search_visible_chapters=await page.locator('.chapter:visible').count();
 await page.locator('nav a[href="#prd"]').click();
 const reset_chapters=await page.locator('.chapter:visible').count();
 await page.setViewportSize({width:390,height:844});
 await page.goto(url);
 await page.screenshot({path:'output/qa/report-mobile.png'});
 const mobile_overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 const result={errors,search_visible_chapters,reset_chapters,mobile_overflow};
 fs.writeFileSync('output/qa/browser-check.json',JSON.stringify(result,null,2));console.log(result);
 await browser.close();
 if(errors.length||mobile_overflow||reset_chapters!==11)process.exit(1);
})().catch(e=>{console.error(e.message);process.exit(1)});
